// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  lessons: [{ type: "autogenerated", dirName: "lessons" }],
  exercises: [{ type: "autogenerated", dirName: "exercises" }],
}

module.exports = sidebars
